/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.MedicineSupplierRole;

import ui.SurgicalPhysicianRole.*;
import ui.MedicalPhysicianRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LabOrganization;
import Business.Organization.MedicalOrganization;
import Business.Organization.MedicineOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.LabOrganization;
import Business.Organization.SurgicalOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author 
 */
public class MedicineSupplierRequestJPanel extends javax.swing.JPanel {
    
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private MedicineOrganization organization;
    private EcoSystem system;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    
    public MedicineSupplierRequestJPanel(JPanel userProcessContainer, UserAccount account, 
            Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = (MedicineOrganization)organization;
        this.system = system;
        
        RoleComboBox.removeAllItems();
        RoleComboBox.addItem("Researcher");
        RoleComboBox.addItem("Pharmacy Pharmacist");       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestTest = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        RoleComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        btnRequestTest.setText("Send");
        btnRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestTestActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMessage.setText("Message:");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTitle.setText("Arranging");

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRole.setText("Role:");

        RoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole)
                            .addComponent(lblMessage)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(lblTitle))
                            .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnRequestTest))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(RoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(549, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(lblRole)
                .addGap(28, 28, 28)
                .addComponent(RoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lblMessage)
                .addGap(18, 18, 18)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnRequestTest)
                .addGap(149, 149, 149))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MedicineSupplierSendJPanel dwjp = (MedicineSupplierSendJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestTestActionPerformed
    String message = txtMessage.getText();
    if(message.equals("") || message.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please enter message for the request");
        return;
    }

    String selectedRole = (String) RoleComboBox.getSelectedItem();    
    LabTestWorkRequest request = new LabTestWorkRequest();
    request.setMessage(message);
    request.setSender(userAccount);
    request.setStatus("Sent");
    request.setTargetRole(selectedRole);

    boolean requestSent = false;

    
    for (Network network : system.getNetworkList()) {
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            
            if (selectedRole.equals("Researcher")) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof LabOrganization) {  
                        org.getWorkQueue().getWorkRequestList().add(request);
                        requestSent = true;
                        JOptionPane.showMessageDialog(null, 
                            "Request sent to Researcher in " + ent.getName() + 
                            ", " + org.getName() + " (" + network.getName() + ")");
                    }
                }
            }
           
            else if (selectedRole.equals("Pharmacy Pharmacist") && 
                     ent.getName().equals(enterprise.getName())) {
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org.getOrganizationType().equals(Organization.Type.PharmacyOrganization)) {
                        org.getWorkQueue().getWorkRequestList().add(request);
                        requestSent = true;
                        JOptionPane.showMessageDialog(null, 
                            "Request sent to Pharmacy Pharmacist in " + ent.getName());
                    }
                }
            }
        }
    }

    if (requestSent) {
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        txtMessage.setText("");
    } else {
        if (selectedRole.equals("Researcher")) {
            JOptionPane.showMessageDialog(null,
                "No Lab Department found in any Medical Company. Please ensure organizations exist.");
        } else {
            JOptionPane.showMessageDialog(null,
                "No Pharmacy Organization found in " + enterprise.getName() + 
                ". Please ensure organization exists.");
        }
    }
       
        

    }//GEN-LAST:event_btnRequestTestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RoleComboBox;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestTest;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
